repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
    -   id: htmlhint
        # optional custom config:
        args: [--config, .htmlhintrc]
    -   id: htmllint
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
    -   id: eslint
        files: \.js
        types: [file]
        additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest
